from . import start
from . import shop
from . import workers
from . import farm
from . import daily
from . import referral
from . import withdraw
from . import stats
from . import admin
from . import language
from . import deposit
from . import profile
